### ISSUE TITLE
Replace "Box" Style with Line Style

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#11]
Make the todo look like lines on a paper rather than boxes

![image](https://user-images.githubusercontent.com/9136094/97294492-5a834480-184e-11eb-8533-ebb0a0773364.png)

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/0a7bd69a5091312ae956fc9bf2f4bedf29eefee7

![image](https://user-images.githubusercontent.com/17470909/97661082-5ead9d00-1aae-11eb-8cd5-fa861688e239.png)
