### ISSUE TITLE
Trigger between Headline and Task is Colon

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#13]
If you change the last character to a colon ":" it becomes a headline. If you remove the colon then it becomes a task.

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/e8d0c95b1511aac4077e825717134fc155e844c2

![donedone2](https://user-images.githubusercontent.com/17470909/97661192-a6ccbf80-1aae-11eb-9905-929c7a696d8b.gif)
