### ISSUE TITLE
Trash Can Color

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#14]
The trash can is too visible, its too dark.

![image](https://user-images.githubusercontent.com/9136094/97294957-ff9e1d00-184e-11eb-9400-3f1b1515089d.png)

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/3d4f2588ee63522310342d7753307167ab4c7afd

![image](https://user-images.githubusercontent.com/17470909/97661238-cb289c00-1aae-11eb-8de2-f7bafcbc01fd.png)
