### ISSUE TITLE
New Functionality "Bookmark"

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#15]
We want to be able to bookmark a task, meaning it should be highlighted. It should have a star button, when its pressed it turns into a bookmark. When you press the bookmark it gets unmarked and turns into the star again. This should only be possible with tasks and not with headlines.

![DoneDone](https://user-images.githubusercontent.com/9136094/97300525-dd100200-1856-11eb-9602-557d07187104.jpg)

**Comment by jbienesdev** [comment]
Added this feature on this commit https://github.com/elexess/DoneDone/commit/79ec20c64ea7e4f7049c15edfe74ae409fa66895
