### ISSUE TITLE
Change Logo and Color Schema

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#16]
Change to the new logo, use the new color schema (red)

![DoneDone](https://user-images.githubusercontent.com/9136094/97300747-282a1500-1857-11eb-884f-ed9a88d6af9e.jpg)

**Comment by dottenbr** [comment]
Also the "Pending" color should be red and not yellow anymore

**Comment by jbienesdev** [comment]
Now resolved at https://github.com/elexess/DoneDone/commit/bc5ef3db97728d3f1773d8b39c6e7fd0386b4261
