### ISSUE TITLE
Add filter "Marked"

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#17]
This will show all tasks which are "marked"

**Comment by jbienesdev** [comment]
@dottenbr is this in relation to the "Bookmark" functionality? Are we gonna label it `Marked` or `Bookmarked`?

**Comment by jbienesdev** [comment]
Added Marked filter on this PR https://github.com/elexess/DoneDone/commit/0c5b75087d6b9f84378fb2d09608b008555d17a0

![image](https://user-images.githubusercontent.com/17470909/98187478-fcd8b180-1f4b-11eb-9423-c140125d92fc.png)
