### ISSUE TITLE
Show Board ID and Button

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#5]
![image](https://user-images.githubusercontent.com/9136094/97292141-25292780-184b-11eb-8218-8dead1feac25.png)

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/00b061bacf4db2baa0f81ea1aba70eb851e33d65
![image](https://user-images.githubusercontent.com/17470909/97660887-ce6f5800-1aad-11eb-8e4c-64363dea1fdc.png)
