### ISSUE TITLE
Remove Whitespace below Filter

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#6]
![image](https://user-images.githubusercontent.com/9136094/97292211-40943280-184b-11eb-9102-73bb9629bd0e.png)

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/8b6a629ad00afa8107d813a23f92c5c16cb17d0d

![image](https://user-images.githubusercontent.com/17470909/97660941-f363cb00-1aad-11eb-9639-c53debec7504.png)
