### ISSUE TITLE
Reduce Logo Padding

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#7]
![image](https://user-images.githubusercontent.com/9136094/97292297-5e619780-184b-11eb-9a30-a266c63896b5.png)

**Comment by jbienesdev** [comment]
Fixed in this commit https://github.com/elexess/DoneDone/commit/762a12d959a3bd3fdd8f4016b08e40298855e94c
![image](https://user-images.githubusercontent.com/17470909/97661013-28701d80-1aae-11eb-86db-3b145243d22c.png)
