### ISSUE TITLE
Remove functionality to delete board

### ISSUE THREAD

**Issue by dottenbr** [elexess/DoneDone#9]
![Clipboard - October 27, 2020 11_57 AM](https://user-images.githubusercontent.com/9136094/97292827-0aa37e00-184c-11eb-9d0f-766f8ef594c1.png)

**Comment by jbienesdev** [comment]
@dottenbr functionality removed from this commit https://github.com/elexess/DoneDone/commit/55621cedb2f75d8398a74ea60ea84c16b9663879
